### ISSUE TITLE
docs: (question) Once a brick is published, is the publisher the only person that can make future updates to that brick?

### ISSUE THREAD

**Issue by Luckey-Elijah** [brick-hub/brickhub.dev#25]
**Description**

I am curious about maintenance for published bricks. When published does a brick require the same publisher for future versions on that brick?

For example, if I publish a brick — `my_brick` — but then want to give the responsibility of publishing to CI/CD or another contributor for future versions of `my_brick`, is it possible?

**Comment by felangel** [comment]
Hi @Luckey-Elijah 👋
Thanks for opening an issue!

At the moment only the original publisher can publish future updates (you can always login to the same user via CI). I’m planning to add the ability to add/remove publishers in the next few days so I’ll keep this issue open in the meantime. Sorry for any inconvenience!

**Comment by felangel** [comment]
You can now manage publishers for your bricks via the new settings tab on the brick details page at https://brickhub.dev 🎉
