### ISSUE TITLE
feat: explicit `latest` url for bricks and/or non-explicit brick URL for latest version

### ISSUE THREAD

**Issue by GroovinChip** [brick-hub/brickhub.dev#29]
**Description**

It would be nice if bricks listings URLs either:
* had an explicit `/latest` URL that resolves to the latest version (e.g., [brickhub.dev/macosui_starter/latest](https://brickhub.dev/bricks/macosui_starter/latest)
* resolved to the latest version by default (e.g., [brickhub.dev/macosui_starter](https://brickhub.dev/bricks/macosui_starter)
This would be helpful when linking to brickhub listings from other places so that we do not have to update those links to point to the latest version of a brick every time it is updated.

**Requirements**

- [ ] Add an explicit `/latest` URL for brick listings that resolves to the latest version
- [ ] Implicitly resolve to the latest version when linking to a listing without specifying a version or `/latest`

**Additional Context**

I link to my `macosui_starter` brick in my [Quick Start guide](https://macosui.dev/docs/getting_started/quick_start#step-2-install-the-starter-template) for `macos_ui` and having to update the site every time I update the brick is a bit of a pain :)

**Comment by felangel** [comment]
Hey @GroovinChip 👋 
Thanks for opening an issue!

I'm planning to make https://brickhub.dev/<brick> resolve to the latest version automatically in the next few days. Sorry for the inconvenience!
