### ISSUE TITLE
feat: Add the ability to change your email address associated to your account

### ISSUE THREAD

**Issue by LukeMoody01** [brick-hub/brickhub.dev#49]
**Description**

It would be nice to have the ability to change the email associated with an account seeing as it is displayed to all users when they view your brick.

**Requirements**

- [ ] User can change email address for their account

**Additional Context**

No additional context needed

**Comment by felangel** [comment]
Hi @LukeMoody01 👋 
Thanks for opening an issue!

I'm currently working on the ability to add/remove publishers and I think that should address this issue. Let me know if you feel that would be sufficient, thanks!

**Comment by LukeMoody01** [comment]
Ah yes! That sounds great!

Just to clarify, would this mean a user (developer) could change their email associated with an account? Either way, I think the concept of organizations would also solve the issue as it would not show an email address!

**Comment by felangel** [comment]
> Ah yes! That sounds great!
> 
> Just to clarify, would this mean a user (developer) could change their email associated with an account? Either way, I think the concept of organizations would also solve the issue as it would not show an email address!

Yeah regarding publishers you would be able to add a new publisher (via email) and/or remove the current publisher. Once organizations are implemented you could create an organization, verify your domain, and the org domain would be used instead of an individual’s email.

**Comment by LukeMoody01** [comment]
> > Ah yes! That sounds great!
> > Just to clarify, would this mean a user (developer) could change their email associated with an account? Either way, I think the concept of organizations would also solve the issue as it would not show an email address!
> 
> Yeah regarding publishers you would be able to add a new publisher (via email) and/or remove the current publisher. Once organizations are implemented you could create an organization, verify your domain, and the org domain would be used instead of an individual’s email.

Okay great! That sounds like it would work perfectly!

Thanks Felix! 👏

**Comment by felangel** [comment]
You can now manage publishers for your bricks via the new settings tab on the brick details page at https://brickhub.dev/ 🎉
