### ISSUE TITLE
How to register your account?

### ISSUE THREAD

**Issue by divyanshub024** [brick-hub/brickhub.dev#5]
There is a way to login through Mson CLI but I don't see any way to register.

**Comment by felangel** [comment]
Hi @divyanshub024 👋
Thanks for opening an issue!

We’ll be doing a closed alpha shortly and you’ll have the ability to join the waitlist. Sorry for the inconvenience and thanks so much for expressing interest! 💙🧱

**Comment by divyanshub024** [comment]
Hey @felangel 👋

Thanks for the info. I would love to try this Alpha version soon. And Best of luck for this Alpha launch. I think whole flutter community is excited about it. 💙

Happy Bricking... 🧱
