### ISSUE TITLE
feat: Ability to change user email address

### ISSUE THREAD

**Issue by realitymolder** [brick-hub/brickhub.dev#65]
**Description**

Add the ability to change the email of the user in brickhub.dev 

**Requirements**

- [ ] Web UI
- [ ] Support in the backend

**Comment by felangel** [comment]
Hi @realitymolder 👋 
Thanks for opening an issue!

You can transfer a brick to a different publisher via the `settings` panel in the brick details page. Let me know if that helps 👍 

![FgFby7pWQAAR65J](https://user-images.githubusercontent.com/8855632/199386441-c8319e5d-c74c-4ba6-bf71-35800ed89778.jpeg)

**Comment by felangel** [comment]
Closing this for now since I believe there are no actionable next steps. Feel free to comment with any follow-up questions and I'm happy to continue the conversation 👍

**Comment by realitymolder** [comment]
> Hi @realitymolder 👋 Thanks for opening an issue!
> 
> You can transfer a brick to a different publisher via the `settings` panel in the brick details page. Let me know if that helps 👍
> 
> ![FgFby7pWQAAR65J](https://user-images.githubusercontent.com/8855632/199386441-c8319e5d-c74c-4ba6-bf71-35800ed89778.jpeg)

Hey, so you mean I have to create a new publisher account? No option to verify a new email?

**Comment by felangel** [comment]
> Hey, so you mean I have to create a new publisher account? No option to verify a new email?

Hey, at the moment you'll need to:
- Request to join the BrickHub alpha with a new email address
- Sign Up
- Verify the email
- Add the new email as a publisher to the existing brick

Once we're out of the closed alpha, this process will be streamlined. Sorry for any inconvenience and let me know if you have any additional questions 👍
